version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5435:5432

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379

  banners:
    build:
      context: ./banners
      dockerfile: Dockerfile
    command: >
      sh -c "while ! ./wait-for-postgres.sh db ./banners -- echo 'PostgreSQL started'; do sleep 1; done && go run cmd/banners/main.go"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - CONFIG_PATH=./config/local.yaml
    ports:
      - 8080:8080
